// <auto-generated />
using System;
using GhostWatch.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostWatch.Api.Data.Migrations
{
    [DbContext(typeof(GhostWatchDbContext))]
    [Migration("20260922230538_AddCapitalPools")]
    partial class AddCapitalPools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToPoolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromPoolId");

                    b.HasIndex("ToPoolId");

                    b.ToTable("CapitalAdjustments");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocatedCapital")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetCapital")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("\"Role\" <> 'Other' AND \"ArchivedAt\" IS NULL");

                    b.ToTable("CapitalPools");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Tracks.EconomyTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCapitalPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCapitalPoolId");

                    b.HasIndex("Status");

                    b.ToTable("EconomyTracks", (string)null);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveIndustryJob", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "JobId");

                    b.ToTable("EveIndustryJobs");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveSection", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "Name");

                    b.ToTable("EveSections");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.EveCharacter", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterOwnerHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedScopesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAuthenticatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("EveCharacters", (string)null);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.EveLocationName", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "LocationId");

                    b.ToTable("EveLocationNames");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.PublicEveLookup", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("PublicEveLookups");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterPlan", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("AccountId");

                    b.ToTable("CharacterPlans");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterTrack", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("CharacterTracks");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.ManagedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagedAccounts");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalAdjustment", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("FromPoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("ToPoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Tracks.EconomyTrack", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("DefaultCapitalPoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveIndustryJob", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveSection", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.EveLocationName", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterPlan", b =>
                {
                    b.HasOne("GhostWatch.Api.Management.ManagedAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithOne()
                        .HasForeignKey("GhostWatch.Api.Management.CharacterPlan", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterTrack", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Track");
                });
#pragma warning restore 612, 618
        }
    }
}
