// <auto-generated />
using System;
using GhostWatch.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhostWatch.Api.Data.Migrations
{
    [DbContext(typeof(GhostWatchDbContext))]
    [Migration("20260923181311_AddAttentionAcknowledgements")]
    partial class AddAttentionAcknowledgements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToPoolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromPoolId");

                    b.HasIndex("ToPoolId");

                    b.ToTable("CapitalAdjustments");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocatedCapital")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetCapital")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("\"Role\" <> 'Other' AND \"ArchivedAt\" IS NULL");

                    b.ToTable("CapitalPools");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Charts.ChartDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChartDefinitions");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Charts.ChartPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChartDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChartDefinitionId");

                    b.HasIndex("PageId");

                    b.HasIndex("PageType", "PageId", "SortOrder");

                    b.ToTable("ChartPlacements", t =>
                        {
                            t.HasCheckConstraint("CK_ChartPlacement_Page", "(PageType = 'Dashboard' AND PageId IS NULL) OR (PageType = 'Track' AND PageId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Planning.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ManualProgress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Planning.TrackStrategy", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId");

                    b.ToTable("TrackStrategies");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Replacement.ReplacementPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedReplacementValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = 1");

                    b.ToTable("ReplacementPackages");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Reporting.AttentionAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AttentionAcknowledgements");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Reporting.TrackKpiSelection", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackId");

                    b.ToTable("TrackKpiSelections");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Runs.EconomicRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualInputCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualJobCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualOtherCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualRevenue")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CapitalPoolId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CapitalTiedUp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConcurrentSlots")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedInputCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedJobCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedOtherCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ManufacturingHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaybookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeToSellDays")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapitalPoolId");

                    b.HasIndex("PlaybookId");

                    b.HasIndex("TrackId");

                    b.ToTable("EconomicRuns");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Runs.RunJob", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "JobId");

                    b.HasIndex("RunId");

                    b.ToTable("RunJobs");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Snapshots.EconomicSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthKey")
                        .IsUnique()
                        .HasFilter("\"MonthKey\" IS NOT NULL");

                    b.ToTable("EconomicSnapshots");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Tracks.EconomyTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCapitalPoolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCapitalPoolId");

                    b.HasIndex("Status");

                    b.ToTable("EconomyTracks", (string)null);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveIndustryJob", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlueprintTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "JobId");

                    b.ToTable("EveIndustryJobs");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveSection", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "Name");

                    b.ToTable("EveSections");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.EveCharacter", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterOwnerHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedScopesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAuthenticatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("EveCharacters", (string)null);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.EveLocationName", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "LocationId");

                    b.ToTable("EveLocationNames");
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.PublicEveLookup", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("PublicEveLookups");
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.EconomicRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EconomicRecords");
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.KnowledgeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CapitalPoolId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ObjectiveId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaybookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedPlaybookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapitalPoolId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("PlaybookId");

                    b.HasIndex("RecordId");

                    b.HasIndex("RelatedPlaybookId");

                    b.HasIndex("RunId");

                    b.HasIndex("TrackId");

                    b.ToTable("KnowledgeLinks", t =>
                        {
                            t.HasCheckConstraint("CK_KnowledgeLink_Owner", "(PlaybookId IS NOT NULL) + (RecordId IS NOT NULL) = 1");

                            t.HasCheckConstraint("CK_KnowledgeLink_Target", "(TrackId IS NOT NULL) + (RunId IS NOT NULL) + (CharacterId IS NOT NULL) + (RelatedPlaybookId IS NOT NULL) + (ObjectiveId IS NOT NULL) + (CapitalPoolId IS NOT NULL) = 1");
                        });
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.Playbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playbooks");
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.PlaybookRevision", b =>
                {
                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkdownBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaybookId", "Version");

                    b.ToTable("PlaybookRevisions");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterPlan", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId");

                    b.HasIndex("AccountId");

                    b.ToTable("CharacterPlans");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterTrack", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("CharacterTracks");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.ManagedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagedAccounts");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Capital.CapitalAdjustment", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("FromPoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("ToPoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Charts.ChartPlacement", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Charts.ChartDefinition", null)
                        .WithMany()
                        .HasForeignKey("ChartDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", null)
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Planning.Objective", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Planning.TrackStrategy", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", null)
                        .WithOne()
                        .HasForeignKey("GhostWatch.Api.Economics.Planning.TrackStrategy", "TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Reporting.TrackKpiSelection", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", null)
                        .WithOne()
                        .HasForeignKey("GhostWatch.Api.Economics.Reporting.TrackKpiSelection", "TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Runs.EconomicRun", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", "CapitalPool")
                        .WithMany()
                        .HasForeignKey("CapitalPoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Knowledge.Playbook", null)
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapitalPool");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Runs.RunJob", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Runs.EconomicRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhostWatch.Api.Eve.Esi.EveIndustryJob", "Job")
                        .WithMany()
                        .HasForeignKey("CharacterId", "JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("GhostWatch.Api.Economics.Tracks.EconomyTrack", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("DefaultCapitalPoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveIndustryJob", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Esi.EveSection", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Eve.Inventory.EveLocationName", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.KnowledgeLink", b =>
                {
                    b.HasOne("GhostWatch.Api.Economics.Capital.CapitalPool", null)
                        .WithMany()
                        .HasForeignKey("CapitalPoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Planning.Objective", null)
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Knowledge.Playbook", null)
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Knowledge.EconomicRecord", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Knowledge.Playbook", null)
                        .WithMany()
                        .HasForeignKey("RelatedPlaybookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Runs.EconomicRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GhostWatch.Api.Knowledge.PlaybookRevision", b =>
                {
                    b.HasOne("GhostWatch.Api.Knowledge.Playbook", null)
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterPlan", b =>
                {
                    b.HasOne("GhostWatch.Api.Management.ManagedAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", null)
                        .WithOne()
                        .HasForeignKey("GhostWatch.Api.Management.CharacterPlan", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GhostWatch.Api.Management.CharacterTrack", b =>
                {
                    b.HasOne("GhostWatch.Api.Eve.EveCharacter", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhostWatch.Api.Economics.Tracks.EconomyTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Track");
                });
#pragma warning restore 612, 618
        }
    }
}
