import {Component,inject,signal} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {FormsModule} from '@angular/forms';
import {DatePipe,KeyValuePipe} from '@angular/common';
import {MatButtonModule} from '@angular/material/button';
import {MetricPipe,ProgrammeSummary} from './economic-reporting';
import {requestError} from './tracks/track-api';
interface Snapshot {id:string;timestamp:string;trigger:string;name:string|null;note:string|null;schemaVersion:number;values?:ProgrammeSummary&{pools:{id:string;name:string;role:string;allocated:number;committed:number|null;available:number|null;lifetimeProfit:number|null;archived:boolean}[];objectives:{id:string;name:string;type:string;status:string;manualProgress:number|null;conditionsJson:string}[]};}
@Component({selector:'app-snapshots',imports:[FormsModule,DatePipe,KeyValuePipe,MatButtonModule,MetricPipe],template:`
<p class="eyebrow">HISTORY / ECONOMIC STATE</p><h1>Economic Snapshots</h1><p class="muted">Immutable values captured from local data. A monthly snapshot is created on startup if this UTC calendar month has none, then checked hourly. Missing past months are never reconstructed.</p>
@if(error()){<p class="error" role="alert">{{error()}} <button mat-button (click)="load()">Reload history</button></p>}
<form class="panel compact-form" (ngSubmit)="take()"><h2>Take Snapshot</h2><label>Snapshot name (optional)<input name="name" [(ngModel)]="name" maxlength="160"></label><label>Snapshot note (optional)<textarea name="note" [(ngModel)]="note" maxlength="20000"></textarea></label><button mat-flat-button [disabled]="busy()">Take Snapshot</button>@if(saved()){<p role="status">Snapshot captured.</p>}</form>
<section class="panel table-wrap"><table><thead><tr><th>Snapshot</th><th>Captured</th><th>Trigger</th><th></th></tr></thead><tbody>@for(row of rows();track row.id){<tr><td>{{row.name??(row.trigger==='AutomaticMonthly'?'Monthly programme state':'Manual programme state')}}</td><td>{{row.timestamp|date:'medium':'UTC'}} UTC</td><td>{{row.trigger==='AutomaticMonthly'?'Automatic monthly':'Manual'}}</td><td><button mat-button (click)="open(row.id)">View {{row.name??'snapshot'}}</button></td></tr>}@empty{<tr><td colspan="4">No snapshots yet.</td></tr>}</tbody></table></section>
@if(selected();as selected){@if(selected.values;as values){<section class="panel"><h2>{{selected.name??'Captured programme state'}}</h2><p>{{selected.timestamp|date:'medium':'UTC'}} UTC · {{selected.trigger==='AutomaticMonthly'?'Automatic monthly':'Manual'}} · Format version {{selected.schemaVersion}}</p><p>{{selected.note}}</p><p class="muted">These stored values do not change when current records are edited. Unknown means data was incomplete at capture time.</p>
<div class="table-wrap"><table><thead><tr><th>Programme metric</th><th>Captured value</th></tr></thead><tbody>@for(item of values.metrics|keyvalue;track item.key){<tr><td>{{label(item.key)}}</td><td>{{item.value|metric:unit(item.key)}}</td></tr>}</tbody></table></div><p>Default package: {{values.replacementPackageName??'None selected'}} · Collected wallets: {{values.facts.walletCount}}/{{values.facts.characterCount}} {{values.facts.walletsStale?'· Stale at capture':''}}</p></section>
<section class="panel"><h2>Captured Capital Pools</h2><div class="table-wrap"><table><thead><tr><th>Pool</th><th>Allocated</th><th>Committed</th><th>Available</th><th>Lifetime P/L</th></tr></thead><tbody>@for(pool of values.pools;track pool.id){<tr><td>{{pool.name}}{{pool.archived?' (archived)':''}}<small>{{pool.role}}</small></td><td>{{pool.allocated|metric}}</td><td>{{pool.committed|metric}}</td><td>{{pool.available|metric}}</td><td>{{pool.lifetimeProfit|metric}}</td></tr>}@empty{<tr><td colspan="5">No pools at capture.</td></tr>}</tbody></table></div></section>
<section class="panel"><h2>Captured Tracks and KPIs</h2>@for(track of values.tracks;track track.id){<details><summary>{{track.name}} · {{track.status}} · {{track.purpose}}</summary><p>Default pool: {{track.poolName??'None'}}</p><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>Selected KPI</th></tr></thead><tbody>@for(item of track.metrics|keyvalue;track item.key){<tr><td>{{label(item.key)}}</td><td>{{item.value|metric:unit(item.key)}}</td><td>{{track.selectedKpis.includes(item.key)?'Selected':''}}</td></tr>}</tbody></table></div></details>}@empty{<p>No Tracks at capture.</p>}</section>
<section class="panel"><h2>Captured Objectives / Gates</h2><ul>@for(objective of values.objectives;track objective.id){<li>{{objective.name}} · {{objective.type}} · {{objective.status}} · {{objective.manualProgress|metric:'%'}} · {{conditions(objective.conditionsJson)}}</li>}@empty{<li>No objectives at capture.</li>}</ul></section>
}}
`,styles:`details{margin:12px 0;}summary{cursor:pointer;}`})
export class Snapshots {
 private readonly http=inject(HttpClient);readonly rows=signal<Snapshot[]>([]);readonly selected=signal<Snapshot|null>(null);readonly error=signal('');readonly busy=signal(false);readonly saved=signal(false);name='';note='';
 private readonly labels:Record<string,string>={coreCapital:'Core Capital',treasury:'Ghost Watch Treasury',rdCapital:'T3 R&D capital',expansionCapital:'Expansion Capital',profit30d:'30-day realised profit',replacementValue:'Default replacement value',replacementCoverage:'Replacement coverage',activeRuns:'Active Runs',completedRuns:'Completed Runs',allocated:'Programme allocation',committed:'Programme commitments',liquid:'Liquid wallets',marketBuyCommitments:'Market buy commitments',sellOrderListedValue:'Sell-order listed value',lifetimeProfit:'Lifetime realised profit',expectedProfit:'Expected profit (open Runs)',capitalAllocated:'Default pool allocation',capitalCommitted:'Track commitments',capitalAvailable:'Default pool available',slotDays:'Slot-days',profitPerSlotDay:'Profit per slot-day',capitalTurnDays:'Average capital turn days',timeToSellDays:'Average time to sell',rdSpend:'Recorded R&D spend',internalisation:'Internalisation'};
 constructor(){this.load();}
 label(key:string){return this.labels[key]??key;}unit(key:string){return key==='replacementCoverage'?'packages':key==='internalisation'?'%':['activeRuns','completedRuns'].includes(key)?'count':['slotDays','capitalTurnDays','timeToSellDays'].includes(key)?'days':key==='profitPerSlotDay'?'ISK/day':'ISK';}
 conditions(json:string){const items=JSON.parse(json) as {Label:string;Done:boolean}[];return `${items.filter(x=>x.Done).length}/${items.length} conditions checked`;}
 load(){this.http.get<Snapshot[]>('/api/economics/snapshots').subscribe({next:rows=>{this.rows.set(rows);this.error.set('');},error:e=>this.error.set(requestError(e))});}
 open(id:string){this.http.get<Snapshot>(`/api/economics/snapshots/${id}`).subscribe({next:row=>{this.selected.set(row);this.error.set('');},error:e=>this.error.set(requestError(e))});}
 take(){this.busy.set(true);this.saved.set(false);this.http.post<{id:string}>('/api/economics/snapshots',{name:this.name,note:this.note}).subscribe({next:row=>{this.busy.set(false);this.saved.set(true);this.load();this.open(row.id);},error:e=>{this.busy.set(false);this.error.set(requestError(e));}});}
}
