import {test,expect} from '@playwright/test';
test('Markdown procedures retain revisions and arbitrary records link to them safely',async({page})=>{
  const name=`Production ${Date.now()}`;
  await page.goto('/playbooks');
  await page.getByLabel('Playbook name',{exact:true}).fill(name);
  await page.getByLabel('Markdown',{exact:true}).fill('# Original procedure\n- [ ] Source materials\n<script>window.unsafeMarkdown=true</script><img src="x" onerror="window.unsafeMarkdown=true">');
  await expect(page.getByRole('heading',{name:'Original procedure'})).toBeVisible();
  expect(await page.evaluate(()=>('unsafeMarkdown' in window))).toBe(false);
  await page.getByRole('button',{name:'Save Playbook',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Document saved');
  await page.getByLabel('Markdown',{exact:true}).fill('# Revised procedure');
  await page.getByRole('button',{name:'Save Playbook',exact:true}).click();
  await expect(page.getByText('Current version: 2.',{exact:false})).toBeVisible();
  await page.reload();
  await page.getByRole('button',{name:`Open ${name}`,exact:true}).click();
  await page.getByText(`Version 1 · ${name}`,{exact:false}).click();
  await expect(page.getByRole('heading',{name:'Original procedure'})).toBeVisible();
  await page.goto('/records');
  await page.getByLabel('Record title',{exact:true}).fill(`Finding ${name}`);
  await page.getByLabel('Record type',{exact:true}).fill('Supplier observation');
  await page.getByLabel('Markdown',{exact:true}).fill('**Preferred supplier**');
  await page.getByText('Related objects',{exact:true}).click();
  await page.getByRole('checkbox',{name:`${name} Open`,exact:true}).check();
  await page.getByRole('button',{name:'Save Record',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Document saved');
  await page.reload();
  await page.getByRole('button',{name:`Open Finding ${name}`,exact:true}).click();
  await page.getByText('Related objects',{exact:true}).click();
  await expect(page.getByRole('checkbox',{name:`${name} Open`,exact:true})).toBeChecked();
});
