import { test, expect } from '@playwright/test';
test('manual Run keeps estimates distinct and supports R&D completion without revenue', async ({ page, request }) => {
  const name = `Research programme ${Date.now()}`;
  const created = await request.post('/api/economics/tracks', { data: {name,description:'',notes:'',status:'Active',purpose:'R&D'} });
  expect(created.ok()).toBe(true);
  await page.goto('/runs/new');
  await page.getByLabel('Run name', {exact:true}).fill('First experimental hull');
  await page.getByRole('combobox',{name:'Track',exact:true}).selectOption({label:name});
  await page.getByRole('combobox',{name:'Run type',exact:true}).selectOption('R&D');
  await page.getByRole('combobox',{name:'Purpose',exact:true}).selectOption('R&D');
  await page.getByLabel('Expected input cost (ISK)',{exact:true}).fill('100');
  await page.getByLabel('Expected job cost (ISK)',{exact:true}).fill('0');
  await page.getByLabel('Expected other cost (ISK)',{exact:true}).fill('0');
  await page.getByLabel('Expected revenue (ISK)',{exact:true}).fill('150');
  await page.getByLabel('Run notes',{exact:true}).fill('Preserve this experiment');
  await page.getByRole('button',{name:'Create Run',exact:true}).click();
  await expect(page).toHaveURL(/\/runs\/[a-f0-9-]{36}$/);
  await expect(page.getByRole('row').filter({hasText:'Expected profit (ISK)'})).toContainText('50.00');
  await expect(page.getByRole('row').filter({hasText:'Actual profit (ISK)'})).toContainText('Unknown');
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('Completed');
  await page.getByRole('combobox',{name:'Verdict',exact:true}).selectOption('R&D Successful');
  await page.getByLabel('Started at (UTC)',{exact:true}).fill('2026-01-01T12:00');
  await page.getByLabel('Completed at (UTC)',{exact:true}).fill('2026-01-02T12:00');
  await page.getByLabel('Actual input cost (ISK)',{exact:true}).fill('80');
  await page.getByLabel('Actual other cost (ISK)',{exact:true}).fill('0');
  await page.getByRole('button',{name:'Save Run',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Run saved');
  await page.reload();
  await expect(page.getByRole('combobox',{name:'Verdict',exact:true})).toHaveValue('R&D Successful');
  await expect(page.getByLabel('Expected revenue (ISK)',{exact:true})).toHaveValue('150');
  await expect(page.getByLabel('Actual revenue (ISK)',{exact:true})).toHaveValue('');
  await expect(page.getByRole('row').filter({hasText:'Actual profit (ISK)'})).toContainText('Unknown');
});

test('industry jobs expose create, associate and remove actions with names', async ({ page }) => {
  let linked = false;
  const id = '11111111-1111-1111-1111-111111111111';
  await page.route('**/api/eve/industry-jobs', route => route.fulfill({json:[{characterId:7,characterName:'Workshop pilot',jobId:42,activityId:1,productName:'Raven',productTypeId:638,blueprintTypeId:681,runs:1,status:'active',startDate:'2026-09-01T00:00:00Z',endDate:'2026-09-02T00:00:00Z',runId:linked?id:null,runName:linked?'Raven batch':null,trackId:linked?id:null,trackName:linked?'Workshop':null}]}));
  await page.route('**/api/economics/runs', route => route.fulfill({json:[{run:{id,name:'Raven batch'},trackName:'Workshop'}]}));
  await page.route(`**/api/economics/runs/${id}/jobs**`, route => {linked=route.request().method()==='POST';return route.fulfill({status:204});});
  await page.goto('/industry-jobs');
  await expect(page.getByRole('cell',{name:'Unassociated',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Create Run',exact:true})).toHaveAttribute('href','/runs/new?characterId=7&jobId=42');
  await page.getByRole('button',{name:'Associate existing Run'}).click();
  await page.getByRole('combobox',{name:'Existing Run',exact:true}).selectOption(id);
  await page.getByRole('button',{name:'Save association'}).click();
  await expect(page.getByRole('link',{name:'Raven batch',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Remove association'}).click();
  await expect(page.getByRole('cell',{name:'Unassociated',exact:true})).toBeVisible();
});
